# Coursera_Capstone_wk_3_part_2 Segmenting and Clustering Neighborhoods in Toronto: Coordinates

### This is the part 2 of the Week-3 Assignment: Dataframe of coordinates.

Build a dataframe of the postal code of each neighborhood along with the borough name and neighborhood name, and the latitude and the longitude coordinates of each neighborhood.

In part 1 of the Week-3 Assignment, we built a dataframe of the postal code of each neighborhood along with the borough name and neighborhood name. We repeat steps here, with output simplified.

In [1]:
import pandas as pd

url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
df_url = pd.read_html(url) # install lxml
df_url # list of a lot of info. [180 rows x 3 columns] and more
df_brnb = df_url[0] # this has what we want: index (0-179), 3 columns (Postal Code, Borough, Neighbourhood)
df_brnb.columns = ["PostalCode", "Borough", "Neighborhood"] #  ["Postal Code", "Borough", "Neighbourhood"] 
df_brnb = df_brnb[df_brnb.Borough != 'Not assigned'] # 103 rows × 3 columns
df_brnb.Neighborhood[df_brnb.Neighborhood=='Not assigned'] = df_brnb.Borough[df_brnb.Neighborhood=='Not assigned']
df_brnb = df_brnb.groupby(['PostalCode','Borough'],as_index=False)['Neighborhood'].apply(', '.join)
print(df_brnb.shape)
df_brnb

(103, 3)

C:\Users\Ron\anaconda38\envs\machine_learning\lib\site-packages\pandas\core\series.py:963: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._where(~key, value, inplace=True)

    PostalCode      Borough                                       Neighborhood
0          M1B  Scarborough                                     Malvern, Rouge
1          M1C  Scarborough             Rouge Hill, Port Union, Highland Creek
2          M1E  Scarborough                  Guildwood, Morningside, West Hill
3          M1G  Scarborough                                             Woburn
4          M1H  Scarborough                                          Cedarbrae
..         ...          ...                                                ...
98         M9N         York                                             Weston
99         M9P    Etobicoke                                          Westmount
100        M9R    Etobicoke  Kingsview Village, St. Phillips, Martin Grove ...
101        M9V    Etobicoke  South Steeles, Silverstone, Humbergate, Jamest...
102        M9W    Etobicoke                Northwest, West Humber - Clairville

[103 rows x 3 columns]

Read into a dataframe a csv file that has the geographical coordinates of each
postal code: http://cocl.us/Geospatial_data. For convenience, we rename column 'Postal Code' read in as 'PostalCode'.

In [2]:
df_coor = pd.read_csv("http://cocl.us/Geospatial_data")
df_coor.columns = ['PostalCode', 'Latitude', 'Longitude']
print(type(df_coor))
print(df_coor.shape)
print(df_coor.index)
print(df_coor.columns)
df_coor.head()

<class 'pandas.core.frame.DataFrame'>
(103, 3)
RangeIndex(start=0, stop=103, step=1)
Index(['PostalCode', 'Latitude', 'Longitude'], dtype='object')

  PostalCode   Latitude  Longitude
0        M1B  43.806686 -79.194353
1        M1C  43.784535 -79.160497
2        M1E  43.763573 -79.188711
3        M1G  43.770992 -79.216917
4        M1H  43.773136 -79.239476

In [3]:
print("df_brnb.shape, df_brnb.columns:")
print(df_brnb.shape)
print(df_brnb.columns)
print("df_coor.shape, df_coor.columns:")
print(df_coor.shape)
print(df_coor.columns)

df_brnb.shape, df_brnb.columns:
(103, 3)
Index(['PostalCode', 'Borough', 'Neighborhood'], dtype='object')
df_coor.shape, df_coor.columns:
(103, 3)
Index(['PostalCode', 'Latitude', 'Longitude'], dtype='object')

*`Direction `* Use the csv file to create the following dataframe:

    The dataframe has number index and 5 columns (PostalCode, Borough, Neighborhood, Latitude, Longitude). 
    
Dataframe df_brnb has 3 columns: PostalCode, Borough, Neighborhood. Dataframe df_coor has 3 columns: PostalCode, Latitude, Longitude. Both have 103 rows. Columns df_brnb.PostalCode and column df_coor.PostalCode are of the same data type 'object' after we check df_brnb.dtypes and df_coor.dtypes.

In [4]:
df_brnb.dtypes, df_coor.dtypes, df_brnb.PostalCode.dtypes == df_coor.PostalCode.dtypes

(PostalCode      object
 Borough         object
 Neighborhood    object
 dtype: object,
 PostalCode     object
 Latitude      float64
 Longitude     float64
 dtype: object,
 True)

Merging/Joining df_brnb and df_coor gives what we want.

In [5]:
df_bnco = pd.merge(df_brnb, df_coor, on='PostalCode')
print(df_bnco.shape)
df_bnco

(103, 5)

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
...,...,...,...,...,...
98,M9N,York,Weston,43.706876,-79.518188
99,M9P,Etobicoke,Westmount,43.696319,-79.532242
100,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ...",43.688905,-79.554724
101,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437
102,M9W,Etobicoke,"Northwest, West Humber - Clairville",43.706748,-79.594054

Now we need to make sure that df_bnco is indeed the dataframe we want. 
We will check no PostalCode is missing in either df_brnb from web or df_coor from csv file. 
This can be verified by comparing merge(df_brnb, df_coor) and merge(df_coor, df_brnb). 
Any missing PostalCode in df_brnb or df_coor will result in different numbers of rows in df_bnco and in, df_cobn.

In [6]:
df_cobn = pd.merge(df_coor, df_brnb, on='PostalCode')
df_cobn
print(all(df_bnco.PostalCode   == df_cobn.PostalCode))
print(all(df_bnco.Borough      == df_cobn.Borough))
print(all(df_bnco.Neighborhood == df_cobn.Neighborhood))
print(all(df_bnco.Latitude     == df_cobn.Latitude))
print(all(df_bnco.Longitude    == df_cobn.Longitude))

True
True
True
True
True

The above True values show that both df_bnco and df_cobn are essentially the same. Now it is sure that every PostalCode in df_brnb and every PostalCode in df_coor are one-to-one mapped: No PostalCode is missing in either dataframe.

`P.S.: (Directions)`

Peer-graded Assignment: Segmenting and Clustering Neighborhoods in Toronto

Project Title *
Give your project a descriptive title

For this assignment, you will be required to explore and cluster the neighborhoods in Toronto.

1. Start by creating a new Notebook for this assignment.
2. Use the Notebook to build the code to scrape the following Wikipedia page, https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M, in order to obtain the data that is in the table of postal codes and to transform the data into a pandas  dataframe like the one shown below:

3. To create the above dataframe:

    - The dataframe will consist of three columns: PostalCode, Borough, and Neighborhood
    - Only process the cells that have an assigned borough. Ignore cells with a borough that is Not assigned.
    - More than one neighborhood can exist in one postal code area. For example, in the table on the Wikipedia page, you will notice that M5A is listed twice and has two neighborhoods: Harbourfront and Regent Park. These two rows will be combined into one row with the neighborhoods separated with a comma as shown in row 11  in the above table.
    - If a cell has a borough but a Not assigned  neighborhood, then the neighborhood will be the same as the borough.
    - Clean your Notebook and add Markdown cells to explain your work and any assumptions you are making.
    - In the last cell of your notebook, use the .shape method to print the number of rows of your dataframe.
4. Submit a link to your Notebook on your Github repository.(10 marks)

Note: There are different website scraping libraries and packages in Python. For scraping the above table, you can simply use pandas  to read the table into a pandas dataframe.

Another way, which would help to learn for more complicated cases of web scraping is using the BeautifulSoup package. Here is the package's main documentation page: http://beautiful-soup-4.readthedocs.io/en/latest/

Use pandas, or the BeautifulSoup package, or any other way you are comfortable with to transform the data in the table on the Wikipedia page into the above pandas dataframe.

​

Now that you have built a dataframe of the postal code of each neighborhood along with the borough name and neighborhood name, in order to utilize the Foursquare location data, we need to get the latitude and the longitude coordinates of each neighborhood. 

In an older version of this course, we were leveraging the Google Maps Geocoding API to get the latitude and the longitude coordinates of each neighborhood. However, recently Google started charging for their API: http://geoawesomeness.com/developers-up-in-arms-over-google-maps-api-insane-price-hike/, so we will use the Geocoder Python package instead: https://geocoder.readthedocs.io/index.html.

The problem with this Package is you have to be persistent sometimes in order to get the geographical coordinates of a given postal code. So you can make a call to get the latitude and longitude coordinates of a given postal code and the result would be None, and then make the call again and you would get the coordinates. So, in order to make sure that you get the coordinates for all of our neighborhoods, you can run a while loop for each postal code. Taking  postal code M5G as an example, your code would look something like this:

    import geocoder # import geocoder
    # initialize your variable to None
    lat_lng_coords = None
    # loop until you get the coordinates
    while(lat_lng_coords is None):
        g = geocoder.google('{}, Toronto, Ontario'.format(postal_code))
        lat_lng_coords = g.latlng
    latitude = lat_lng_coords[0]
    longitude = lat_lng_coords[1]


Given that this package can be very unreliable, in case you are not able to get the geographical coordinates of the neighborhoods using the Geocoder package, here is a link to a csv file that has the geographical coordinates of each postal code: http://cocl.us/Geospatial_data

Use the Geocoder package or the csv file to create the following dataframe:

    The dataframe has number index and 5 columns (PostalCode, Borough, Neighborhood, Latitude, Longitude). 

Important Note: There is a limit on how many times you can call geocoder.google function. It is 2500 times per day. This should be way more than enough for you to get acquainted with the package and to use it to get the geographical coordinates of the neighborhoods in the Toronto.

Once you are able to create the above dataframe, submit a link to the new Notebook on your Github repository. (2 marks)

Note: While including the link do not copy paste the URL. Use the embedded link option in the formatting  tools of the Response field to include the link. Check the  displayed in image below

​

Explore and cluster the neighborhoods in Toronto. You can decide to work with only boroughs that contain the word Toronto and then replicate the same analysis we did to the New York City data. It is up to you. 

Just make sure:

    1. to add enough Markdown cells to explain what you decided to do and to report any observations you make. 
    2. to generate maps to visualize your neighborhoods and how they cluster together. 
Once you are happy with your analysis, submit a link to the new Notebook on your Github repository. (3 marks)

### Shape and Brief View of the DataFrame

In conclusion, df_bnco is the dataframe required in part 2 of the assinment in week-3. Some properties are re-printed below:

In [7]:
print(df_bnco.shape)
df_bnco

(103, 5)

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
...,...,...,...,...,...
98,M9N,York,Weston,43.706876,-79.518188
99,M9P,Etobicoke,Westmount,43.696319,-79.532242
100,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ...",43.688905,-79.554724
101,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437
102,M9W,Etobicoke,"Northwest, West Humber - Clairville",43.706748,-79.594054